
---
- name: Update repositories cache and install "ubuntu" package
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Update repositories cache and install "RedHat" package
  ansible.builtin.yum:
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: install the latest version of redis on CentOS
  yum:
    name: redis
    state: latest
  when: ansible_os_family == "RedHat"

- name: install the latest version of redis on Debian
  apt: 
    name: redis
    state: latest
  when: ansible_os_family == "Debian"

- name: Start Redis service
  service:
    name: redis-server
    state: started
    enabled: yes


