
---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Redis
  apt:
    name: redis-server
    state: present

- name: Start Redis service
  service:
    name: redis-server
    state: started
    enabled: yes


