name: Pull Request Notification
on:
  pull_request:
    types: [opened, reopened, closed, edited, ready_for_review]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: bhavinmpanchal91@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Pull Request Notification"
          to: bhavinmpanchal19@gmail.com
          from: "bhavinmpanchal91@gmail.com"
          body: |
            A pull request has been submitted/updated/closed in the repository.
            Repository: ${{ github.repository }}
            Pull Request: ${{ github.event.pull_request.html_url }}
            Author: ${{ github.event.pull_request.user.login }}
            Action: ${{ github.event.action }}
